# Generated by Django 5.1.3 on 2025-01-15 06:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('num_seguridad_social', models.CharField(max_length=20, unique=True)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.areaespecialidad')),
                ('doctor_actual', models.ForeignKey(limit_choices_to={'tipoUsuario': 'DR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_doctor', to=settings.AUTH_USER_MODEL)),
                ('enfermero_actual', models.ForeignKey(limit_choices_to={'tipoUsuario': 'EN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_enfermero', to=settings.AUTH_USER_MODEL)),
                ('hospital_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarioJefa.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('diagnostico', models.TextField()),
                ('doctor', models.ForeignKey(limit_choices_to={'tipoUsuario': 'DR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_medico', to='usuarioJefa.paciente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEnfermeros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('motivo_cambio', models.TextField(blank=True, null=True)),
                ('enfermero', models.ForeignKey(limit_choices_to={'tipoUsuario': 'EN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_enfermeros', to='usuarioJefa.paciente')),
            ],
            options={
                'verbose_name': 'Historial de Enfermeros',
                'verbose_name_plural': 'Historiales de Enfermeros',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialDoctores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('motivo_cambio', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'tipoUsuario': 'DR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_doctores', to='usuarioJefa.paciente')),
            ],
            options={
                'verbose_name': 'Historial de Doctores',
                'verbose_name_plural': 'Historiales de Doctores',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='RecetaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('prescripcion', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'tipoUsuario': 'DR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='usuarioJefa.paciente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
