# Generated by Django 5.1.3 on 2025-01-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioJefa', '0002_compuesto_instrumento_alter_recetamedica_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='gramaje',
            field=models.CharField(max_length=50),
        ),
    ]
