# Generated by Django 5.1.3 on 2025-01-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioJefa', '0003_alter_medicamento_gramaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='numero_ingresos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='hospital_origen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
