# Generated by Django 5.1.3 on 2025-01-21 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioJefa', '0004_paciente_numero_ingresos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCompletoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial_completo', to='usuarioJefa.paciente')),
            ],
        ),
    ]
