# Generated by Django 5.1.3 on 2025-01-24 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('usuarioJefa', '0006_asignacioncalendario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio_anterior', models.DateField()),
                ('fecha_fin_anterior', models.DateField()),
                ('fecha_inicio_nueva', models.DateField()),
                ('fecha_fin_nueva', models.DateField()),
                ('area_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_anteriores', to='login.areaespecialidad')),
                ('area_nueva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_nuevos', to='login.areaespecialidad')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarioJefa.asignacioncalendario')),
            ],
            options={
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
