# Generated by Django 5.1.3 on 2025-01-24 15:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_usuarios_tipousuario'),
        ('usuarioJefa', '0008_areasobrecarga_gravedadpaciente_nivelprioridadarea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistribucionPacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('pacientes_gravedad_1', models.IntegerField(default=0, help_text='Pacientes de gravedad baja (máx. 3)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('pacientes_gravedad_2', models.IntegerField(default=0, help_text='Pacientes de gravedad media (máx. 2)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('pacientes_gravedad_3', models.IntegerField(default=0, help_text='Pacientes de gravedad alta (máx. 1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.areaespecialidad')),
                ('enfermero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Distribución de Pacientes',
                'verbose_name_plural': 'Distribuciones de Pacientes',
                'unique_together': {('enfermero', 'area')},
            },
        ),
    ]
