# Generated by Django 5.1.3 on 2025-05-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioJefa', '0009_distribucionpacientes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distribucionpacientes',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='distribucionpacientes',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='distribucionpacientes',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
