# Generated by Django 5.1.3 on 2025-05-09 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioJefa', '0010_alter_distribucionpacientes_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('distribucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='usuarioJefa.distribucionpacientes')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarioJefa.paciente')),
            ],
            options={
                'verbose_name': 'Asignación de Paciente',
                'verbose_name_plural': 'Asignaciones de Pacientes',
                'unique_together': {('distribucion', 'paciente')},
            },
        ),
    ]
