# Generated by Django 5.1.3 on 2025-05-09 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioJefa', '0011_asignacionpaciente'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asignacionpaciente',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='asignacionpaciente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacionpaciente', to='usuarioJefa.paciente'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionpaciente',
            unique_together={('paciente', 'distribucion')},
        ),
    ]
