# Generated by Django 5.1.3 on 2025-05-28 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_usuarios_areaespecialidad_and_more'),
        ('usuarioJefa', '0012_alter_asignacionpaciente_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(help_text='Inicio de la asignación temporal')),
                ('fecha_fin', models.DateTimeField(help_text='Fin de la asignación temporal')),
                ('motivo', models.TextField(help_text='Razón de la asignación de emergencia')),
                ('activa', models.BooleanField(default=True, help_text='Si la asignación de emergencia está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('area_destino', models.ForeignKey(help_text='Área a donde va temporalmente', on_delete=django.db.models.deletion.CASCADE, related_name='emergencias_destino', to='login.areaespecialidad')),
                ('area_origen', models.ForeignKey(help_text='Área de donde viene el enfermero', on_delete=django.db.models.deletion.CASCADE, related_name='emergencias_origen', to='login.areaespecialidad')),
                ('creada_por', models.ForeignKey(limit_choices_to={'tipoUsuario': 'JP'}, on_delete=django.db.models.deletion.CASCADE, related_name='emergencias_creadas', to=settings.AUTH_USER_MODEL)),
                ('enfermero', models.ForeignKey(limit_choices_to={'tipoUsuario': 'EN'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Emergencia',
                'verbose_name_plural': 'Asignaciones de Emergencia',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
