# Generated by Django 5.1.3 on 2025-05-28 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_usuarios_areaespecialidad_and_more'),
        ('usuarioJefa', '0013_asignacionemergencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asignacioncalendario',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='asignacioncalendario',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('enfermero', 'fecha_inicio', 'fecha_fin'), name='unique_active_assignment'),
        ),
    ]
