# Generated by Django 5.1.3 on 2025-06-09 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_usuarios_areaespecialidad_and_more'),
        ('usuarioDoctor', '0006_add_ingreso_number'),
        ('usuarioJefa', '0014_alter_asignacioncalendario_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSimulada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_enfermeros', models.IntegerField(default=0, help_text='Cantidad de enfermeros asignados en la simulación')),
                ('cantidad_pacientes', models.IntegerField(default=0, help_text='Cantidad de pacientes en esta área')),
                ('en_sobrecarga', models.BooleanField(default=False, help_text='Si el área está marcada como sobrecargada')),
                ('carga_trabajo_area', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ratio_pacientes_enfermero', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('area_real', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.areaespecialidad')),
            ],
            options={
                'verbose_name': 'Área Simulada',
                'verbose_name_plural': 'Áreas Simuladas',
            },
        ),
        migrations.CreateModel(
            name='EnfermeroSimulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacientes_asignados', models.IntegerField(default=0, help_text='Cantidad de pacientes asignados a este enfermero')),
                ('carga_trabajo_individual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('area_simulada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermeros_asignados', to='usuarioJefa.areasimulada')),
                ('enfermero_real', models.ForeignKey(limit_choices_to={'tipoUsuario': 'EN'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enfermero Simulado',
                'verbose_name_plural': 'Enfermeros Simulados',
                'unique_together': {('area_simulada', 'enfermero_real')},
            },
        ),
        migrations.CreateModel(
            name='PacienteSimulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_simulado', models.CharField(help_text='Nombre generado: Paciente 1, Paciente 2, etc.', max_length=100)),
                ('nivel_gravedad', models.IntegerField(choices=[(1, 'Leve'), (2, 'Moderado'), (3, 'Grave')], default=1)),
                ('area_simulada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes_simulados', to='usuarioJefa.areasimulada')),
                ('enfermero_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_a_cargo', to='usuarioJefa.enfermerosimulado')),
            ],
            options={
                'verbose_name': 'Paciente Simulado',
                'verbose_name_plural': 'Pacientes Simulados',
            },
        ),
        migrations.CreateModel(
            name='SimulacionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre/etiqueta para identificar la simulación', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la simulación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True, help_text='Si la simulación está activa para comparaciones')),
                ('total_areas', models.IntegerField(default=0)),
                ('total_enfermeros', models.IntegerField(default=0)),
                ('total_pacientes', models.IntegerField(default=0)),
                ('carga_trabajo_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('creada_por', models.ForeignKey(limit_choices_to={'tipoUsuario': 'JP'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simulación de Evento',
                'verbose_name_plural': 'Simulaciones de Eventos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='areasimulada',
            name='simulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_simuladas', to='usuarioJefa.simulacionevento'),
        ),
        migrations.CreateModel(
            name='PadecimientoSimulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padecimientos', to='usuarioJefa.pacientesimulado')),
                ('padecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarioDoctor.padecimiento')),
            ],
            options={
                'verbose_name': 'Padecimiento Simulado',
                'verbose_name_plural': 'Padecimientos Simulados',
                'unique_together': {('paciente_simulado', 'padecimiento')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='areasimulada',
            unique_together={('simulacion', 'area_real')},
        ),
    ]
