# Generated by Django 5.1.3 on 2025-06-23 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_fortaleza_options_remove_fortaleza_area_and_more'),
        ('usuarioJefa', '0015_areasimulada_enfermerosimulado_pacientesimulado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin (opcional)')),
                ('tiempo_indefinido', models.BooleanField(default=False, verbose_name='Tiempo indefinido')),
                ('activo', models.BooleanField(default=True)),
                ('desactivado_automaticamente', models.BooleanField(default=False)),
                ('fecha_desactivacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_desactivacion', models.TextField(blank=True)),
                ('motivo_asignacion', models.TextField(verbose_name='Motivo de la asignación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fue_reactivado', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.areaespecialidad', verbose_name='Área asignada')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_temporal_creado', to=settings.AUTH_USER_MODEL)),
                ('reactivado_desde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactivaciones', to='usuarioJefa.personaltemporal')),
            ],
            options={
                'verbose_name': 'Personal Temporal',
                'verbose_name_plural': 'Personal Temporal',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPersonalTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creacion', 'Creación'), ('reactivacion', 'Reactivación'), ('desactivacion', 'Desactivación')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True)),
                ('automatico', models.BooleanField(default=False)),
                ('usuario_accion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('personal_temporal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='usuarioJefa.personaltemporal')),
            ],
            options={
                'verbose_name': 'Historial Personal Temporal',
                'ordering': ['-fecha'],
            },
        ),
    ]
