# Generated by Django 5.1.3 on 2025-06-27 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioJefa', '0016_personaltemporal_historialpersonaltemporal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioMedicamentoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_formulario', models.CharField(help_text='Nombre para identificar este formulario', max_length=200)),
                ('nombre_medicamento', models.CharField(max_length=200)),
                ('presentacion', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_solicitud', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='borrador', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo_firma', models.CharField(choices=[('impresa', 'Imprimir (sin firma)'), ('digital', 'Firma Digital'), ('dibujada', 'Firma Dibujada')], default='impresa', max_length=20)),
                ('firma_digital', models.TextField(blank=True, help_text='Contenido de la firma digital', null=True)),
                ('firma_dibujada', models.TextField(blank=True, help_text='Datos de la firma dibujada en base64', null=True)),
                ('es_plantilla', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(limit_choices_to={'tipoUsuario': 'JF'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plantilla_base', models.ForeignKey(blank=True, help_text='Formulario base si fue creado desde una plantilla', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarioJefa.formulariomedicamentoexterno')),
            ],
            options={
                'verbose_name': 'Formulario de Medicamento Externo',
                'verbose_name_plural': 'Formularios de Medicamentos Externos',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialFormularioExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='usuarioJefa.formulariomedicamentoexterno')),
                ('usuario_cambio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Formulario Externo',
                'verbose_name_plural': 'Historiales de Formularios Externos',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionMedicamentoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nuevo_formulario', 'Nuevo formulario creado'), ('formulario_enviado', 'Formulario enviado'), ('formulario_aprobado', 'Formulario aprobado'), ('formulario_rechazado', 'Formulario rechazado')], max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarioJefa.formulariomedicamentoexterno')),
                ('usuario_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación de Medicamento Externo',
                'verbose_name_plural': 'Notificaciones de Medicamentos Externos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('confirmada', models.BooleanField(default=False)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarioJefa.medicamento')),
                ('solicitante', models.ForeignKey(limit_choices_to={'tipoUsuario__in': ['JF', 'EN']}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Medicamento',
                'verbose_name_plural': 'Solicitudes de Medicamentos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('solicitud', 'Solicitud a farmacia'), ('confirmacion', 'Confirmación de entrega')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True)),
                ('instrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarioJefa.instrumento')),
                ('medicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarioJefa.medicamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('solicitud_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarioJefa.solicitudmedicamento')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
