# Generated by Django 5.1.3 on 2025-06-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioJefa', '0017_formulariomedicamentoexterno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacionmedicamentoexterno',
            name='formulario',
        ),
        migrations.RemoveField(
            model_name='notificacionmedicamentoexterno',
            name='usuario_destinatario',
        ),
        migrations.RemoveField(
            model_name='formulariomedicamentoexterno',
            name='estado',
        ),
        migrations.DeleteModel(
            name='HistorialFormularioExterno',
        ),
        migrations.DeleteModel(
            name='NotificacionMedicamentoExterno',
        ),
    ]
