# Generated by Django 5.1.3 on 2025-01-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaespecialidad',
            name='fortalezas',
            field=models.ManyToManyField(blank=True, to='login.fortaleza'),
        ),
    ]
