# Generated by Django 5.1.3 on 2025-01-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_areaespecialidad_fortalezas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
