# Generated by Django 5.1.3 on 2025-01-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_usuarios_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='fortalezas',
            field=models.ManyToManyField(to='login.fortaleza'),
        ),
    ]
