# Generated by Django 5.1.3 on 2025-01-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_usuarios_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tipoUsuario',
            field=models.CharField(choices=[('JP', 'Jefa de Piso'), ('EN', 'Enfermería'), ('DR', 'Doctor')], default='EN', max_length=2),
        ),
    ]
