# Generated by Django 5.1.3 on 2025-05-07 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_usuarios_tipousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='areaEspecialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.areaespecialidad'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fortalezas',
            field=models.ManyToManyField(blank=True, to='login.fortaleza'),
        ),
    ]
