# Generated by Django 5.1.3 on 2025-06-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_fortaleza_options_fortaleza_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fortaleza',
            options={'ordering': ['nombre'], 'verbose_name': 'Fortaleza', 'verbose_name_plural': 'Fortalezas'},
        ),
        migrations.RemoveField(
            model_name='fortaleza',
            name='area',
        ),
        migrations.AddField(
            model_name='fortaleza',
            name='areas',
            field=models.ManyToManyField(blank=True, help_text='Áreas hospitalarias donde se aplica esta fortaleza', related_name='fortalezas_relacionadas', to='login.areaespecialidad'),
        ),
    ]
