# Generated by Django 5.1.3 on 2025-01-17 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarioDoctor', '0005_alter_padecimiento_options_padecimiento_activo'),
        ('usuarioJefa', '0003_alter_medicamento_gramaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoCuidados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarioJefa.paciente')),
                ('registrado_por', models.ForeignKey(limit_choices_to={'tipoUsuario__in': ['EN', 'JP']}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento de Cuidados',
                'verbose_name_plural': 'Seguimientos de Cuidados',
            },
        ),
        migrations.CreateModel(
            name='RegistroMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrado', models.BooleanField(default=False)),
                ('fecha_administracion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarioDoctor.detallereceta')),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarioEnfermeria.seguimientocuidados')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCuidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('cuidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarioDoctor.recetacuidado')),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarioEnfermeria.seguimientocuidados')),
            ],
        ),
    ]
