# Generated by Django 5.1.3 on 2025-01-19 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioDoctor', '0005_alter_padecimiento_options_padecimiento_activo'),
        ('usuarioEnfermeria', '0002_formularioseguimiento_evaluacionpadecimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentoFaltante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_reportado', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarioEnfermeria.formularioseguimiento')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarioDoctor.detallereceta')),
            ],
        ),
    ]
