# Generated by Django 5.1.3 on 2025-01-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioDoctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallereceta',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='detallereceta',
            name='horario',
        ),
        migrations.AddField(
            model_name='detallereceta',
            name='cantidad_por_toma',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallereceta',
            name='dias_tratamiento',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallereceta',
            name='frecuencia_horas',
            field=models.PositiveIntegerField(default=8, help_text='Cada cuántas horas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallereceta',
            name='unidad_medida',
            field=models.CharField(choices=[('TAB', 'Tabletas'), ('ML', 'Mililitros'), ('MG', 'Miligramos'), ('CAP', 'Cápsulas'), ('GOT', 'Gotas'), ('AMP', 'Ampolletas')], default='AMP', max_length=3),
            preserve_default=False,
        ),
    ]
