# Generated by Django 5.1.3 on 2025-06-15 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_fortaleza_options_fortaleza_area'),
        ('usuarioDoctor', '0006_add_ingreso_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='padecimiento',
            options={'ordering': ['area__nombre', 'nombre'], 'verbose_name': 'Padecimiento', 'verbose_name_plural': 'Padecimientos'},
        ),
        migrations.AddField(
            model_name='padecimiento',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Área hospitalaria donde se maneja principalmente este padecimiento', null=True, on_delete=django.db.models.deletion.PROTECT, to='login.areaespecialidad'),
        ),
        migrations.AddField(
            model_name='padecimiento',
            name='fortalezas',
            field=models.ManyToManyField(blank=True, help_text='Fortalezas de enfermería necesarias para atender este padecimiento', related_name='padecimientos_relacionados', to='login.fortaleza'),
        ),
    ]
