# Generated by Django 5.1.3 on 2025-06-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_fortaleza_options_remove_fortaleza_area_and_more'),
        ('usuarioDoctor', '0007_alter_padecimiento_options_padecimiento_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='padecimiento',
            options={'ordering': ['nombre'], 'verbose_name': 'Padecimiento', 'verbose_name_plural': 'Padecimientos'},
        ),
        migrations.RemoveField(
            model_name='padecimiento',
            name='area',
        ),
        migrations.AddField(
            model_name='padecimiento',
            name='areas',
            field=models.ManyToManyField(blank=True, help_text='Áreas hospitalarias donde se maneja este padecimiento', related_name='padecimientos_relacionados', to='login.areaespecialidad'),
        ),
        migrations.AlterField(
            model_name='padecimiento',
            name='fortalezas',
            field=models.ManyToManyField(blank=True, help_text='Fortalezas de enfermería necesarias para atender este padecimiento', related_name='padecimientos_asociados', to='login.fortaleza'),
        ),
    ]
